### ISSUE TITLE
Add Homebrew formula for macOS users

### ISSUE THREAD

**Issue by alexmt** [iridakos/goto#9]
It would be great if goto was available via [Homebrew](https://brew.sh/) on macOS

**Comment by iridakos** [comment]
Hi @alexmt !

Yes that would be great. I will add this to the current milestone :)

**Comment by iridakos** [comment]
https://github.com/iridakos/goto/releases/tag/v1.2.2

**Comment by iridakos** [comment]
Created [PR in Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core/pull/25281) 🤞

**Comment by iridakos** [comment]
Unfortunately the [build](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/20341/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/audit_goto___online___new_formula/) breaks because the repo is less than 30 days old.

PR: [https://github.com/Homebrew/homebrew-core/pull/25281](https://github.com/Homebrew/homebrew-core/pull/25281)
